global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:5000']
    metrics_path: '/metrics'

  - job_name: 'user-profile-service'
    static_configs:
      - targets: ['user-profile-service:5000']
    metrics_path: '/metrics'

  - job_name: 'prescription-service'
    static_configs:
      - targets: ['prescription-service:5000']
    metrics_path: '/metrics'

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:5000']
    metrics_path: '/metrics'

  - job_name: 'pharmacy-service'
    static_configs:
      - targets: ['pharmacy-service:5000']
    metrics_path: '/metrics'

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['medihelp_redis-exporter:9121']

